/**
 * `cloudflare:workers`, for the Next.js app's type-check only.
 *
 * The app's service binding is typed from the ledger's own source
 * (`Service<typeof import("./workers/group-ledger/src/index").LedgerService>`,
 * generated by `wrangler types` with both configs). So the app's program reads
 * that file, which imports `cloudflare:workers`. That module exists only in
 * the workerd runtime types, which the app can't load (the DOM clash, ADR-0015
 * §4).
 *
 * This declares just the two classes the ledger uses, from the **importable**
 * `@cloudflare/workers-types` namespace. It's a script, with no top-level
 * import, so it declares an ambient module rather than augmenting one.
 */
declare module "cloudflare:workers" {
	type Module = typeof import("@cloudflare/workers-types/index.ts").CloudflareWorkersModule;
	export const DurableObject: Module["DurableObject"];
	export type DurableObject<Env = unknown, Props = object> = import("@cloudflare/workers-types/index.ts").CloudflareWorkersModule.DurableObject<Env, Props>;
	export const WorkerEntrypoint: Module["WorkerEntrypoint"];
	export type WorkerEntrypoint<Env = unknown, Props = object> = import("@cloudflare/workers-types/index.ts").CloudflareWorkersModule.WorkerEntrypoint<Env, Props>;
}
