/**
 * Splitr's database schema — the single definition, for the life of the project.
 *
 * `REQ-D.1` fixes this path: `src/db/schema.ts`, written with Drizzle. It is
 * created here in Cluster B rather than Cluster D because Better Auth needs
 * tables from the first sign-up, and writing them twice — once for local SQLite
 * and again for D1 — is the failure ADR-0009 exists to avoid.
 *
 * ## Where this came from
 *
 * The four tables below (`user`, `session`, `account`, `verification`) and their
 * relations were **generated**, not written:
 *
 *     npx auth@1.7.5 generate --config src/lib/auth.ts --output src/db/schema.ts
 *
 * They are Better Auth's contract. Do not hand-edit their columns. If auth
 * config changes (a plugin, a social provider, an extra user field), re-run the
 * generator and review the diff — that is the supported path. `REQ-M.3` still
 * applies: the generated output was read line by line before being committed.
 *
 * ## Cluster D
 *
 * Nothing in this file changes when D1 arrives. `drizzle-orm/sqlite-core` is the
 * same dialect for `better-sqlite3` and for D1; only `src/db/index.ts` swaps its
 * driver. Migration files are deliberately **not** generated yet — Cluster B
 * creates its throwaway local tables with `drizzle-kit push`, so that
 * `REQ-D.1`'s "first migration generated by `drizzle-kit generate`" is genuinely
 * the first. See ADR-0009.
 *
 * ## Conventions for Splitr's own tables
 *
 * When `group`, `group_member`, `expense`, `line_item` and `settlement` arrive
 * (Cluster D), they follow these rules. They are written down now, while the
 * file is empty of domain tables, because they are expensive to retrofit:
 *
 * - **Money is integer cents.** `integer("amount_cents").notNull()`. Never a
 *   float, never a decimal string. A balance that is off by a rounding error is
 *   the exact failure Splitr exists to prevent.
 * - **Currency is a separate column** (`text("currency")`, ISO 4217, 3 chars).
 *   Cents are meaningless without it.
 * - **Timestamps are unix seconds, UTC.** `integer("created_at").notNull()` —
 *   the raw integer, not Drizzle's `{ mode: "timestamp" }` wrapper, so what is
 *   stored is exactly what is read back on both Node and Workers.
 *   ⚠️ The auth tables below break this: Better Auth generates
 *   `{ mode: "timestamp_ms" }` and owns those columns. That inconsistency is
 *   the library's, it is deliberate, and it stops at the auth tables.
 * - **Ids are `text` ULIDs/UUIDs**, matching Better Auth's `text` ids, so
 *   foreign keys onto `user.id` need no casting.
 * - **Every foreign key is declared** with an explicit `onDelete`, and every
 *   column used in a WHERE clause gets an index. D1 is SQLite: a missing index
 *   is a full scan.
 * - **No `real`, no `blob`, no JSON columns** without an ADR. Receipt images go
 *   to R2 and only the object key is persisted (`REQ-D.3`).
 */

import { relations, sql } from "drizzle-orm";
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = sqliteTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = sqliteTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
