/**
 * Splitr's database schema — the single definition, for the life of the project.
 *
 * `REQ-D.1` fixes this path: `src/db/schema.ts`, written with Drizzle. It is
 * created here in Cluster B rather than Cluster D because Better Auth needs
 * tables from the first sign-up, and writing them twice — once for local SQLite
 * and again for D1 — is the failure ADR-0009 exists to avoid.
 *
 * ## Where this came from
 *
 * The four tables below (`user`, `session`, `account`, `verification`) and their
 * relations were **generated**, not written:
 *
 *     npx auth@1.7.5 generate --config src/lib/auth.ts --output src/db/schema.ts
 *
 * They are Better Auth's contract. Do not hand-edit their columns. If auth
 * config changes (a plugin, a social provider, an extra user field), re-run the
 * generator and review the diff — that is the supported path. `REQ-M.3` still
 * applies: the generated output was read line by line before being committed.
 *
 * ## Migrations
 *
 * `REQ-D.1`'s first migration, generated by `drizzle-kit generate` into
 * `./drizzle/`, creates **every** table in this file, auth and domain alike.
 * Before it, Cluster B used `drizzle-kit push` (ADR-0009) and Cluster C applied
 * exported DDL (ADR-0015); neither wrote a migration file, so this one is
 * genuinely the first. From here on, a schema change is a new generated
 * migration. A migration that has been applied is never edited (`REQ-D.5`).
 *
 * ## Conventions for Splitr's own tables
 *
 * When `group`, `group_member`, `expense`, `line_item` and `settlement` arrive
 * (Cluster D), they follow these rules. They are written down now, while the
 * file is empty of domain tables, because they are expensive to retrofit:
 *
 * - **Money is integer cents.** `integer("amount_cents").notNull()`. Never a
 *   float, never a decimal string. A balance that is off by a rounding error is
 *   the exact failure Splitr exists to prevent.
 * - **Currency is a separate column** (`text("currency")`, ISO 4217, 3 chars).
 *   Cents are meaningless without it.
 * - **Timestamps are unix seconds, UTC.** `integer("created_at").notNull()` —
 *   the raw integer, not Drizzle's `{ mode: "timestamp" }` wrapper, so what is
 *   stored is exactly what is read back on both Node and Workers.
 *   ⚠️ The auth tables below break this: Better Auth generates
 *   `{ mode: "timestamp_ms" }` and owns those columns. That inconsistency is
 *   the library's, it is deliberate, and it stops at the auth tables.
 * - **Ids are `text` ULIDs/UUIDs**, matching Better Auth's `text` ids, so
 *   foreign keys onto `user.id` need no casting.
 * - **Every foreign key is declared** with an explicit `onDelete`, and every
 *   column used in a WHERE clause gets an index. D1 is SQLite: a missing index
 *   is a full scan.
 * - **No `real`, no `blob`, no JSON columns** without an ADR. Receipt images go
 *   to R2 and only the object key is persisted (`REQ-D.3`).
 */

import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";

import { CATEGORY_KEYS, UNCATEGORISED } from "../lib/categories";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = sqliteTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = sqliteTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

/* ========================================================================== *
 * Splitr's domain (REQ-D.1). The decisions behind every table are in ADR-0018.
 *
 * Conventions from the header apply: integer minor units, ISO currency beside
 * every amount, Unix-second timestamps, text ids, declared foreign keys. Every
 * foreign key is `restrict`: in Splitr nothing is ever deleted (expenses are
 * voided, members leave, settlements are immutable), so a delete that would
 * cascade is a bug, and SQLite should refuse it.
 *
 * `CHECK`s encode the rules that need only the row itself. Rules that need
 * other rows (membership, the currency matching the group's, the balance
 * check) live in code and, from Cluster E, in the Durable Object.
 * ========================================================================== */

/** The current time in Unix seconds, for a `default`: the raw integer, per the convention. */
const nowUnixSeconds = sql`(unixepoch())`;

/** SQL list of the allowed categories, from the one shared definition. */
const categoryList = sql.raw(CATEGORY_KEYS.map((key) => `'${key}'`).join(", "));

/**
 * A group of people who share costs. Named `group`, which is an SQL keyword:
 * Drizzle always quotes identifiers, but hand-written SQL (`wrangler d1
 * execute`) must write `"group"`.
 */
export const group = sqliteTable(
  "group",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    /** ISO 4217. One currency per group; no exchange rates (ADR-0018 §4). */
    currency: text("currency").notNull(),
    /** The reusable, rotatable code in the `/join/[code]` link (ADR-0018 §5). */
    inviteCode: text("invite_code").notNull().unique(),
    createdBy: text("created_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdAt: integer("created_at").notNull().default(nowUnixSeconds),
  },
  (table) => [check("group_currency_iso", sql`length(${table.currency}) = 3`)],
);

/**
 * Who belongs to a group. A member may leave only when square (ADR-0018 §6):
 * `left_at` is set, and the row stays, because their past expenses still name
 * them.
 */
export const groupMember = sqliteTable(
  "group_member",
  {
    groupId: text("group_id")
      .notNull()
      .references(() => group.id, { onDelete: "restrict" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    joinedAt: integer("joined_at").notNull().default(nowUnixSeconds),
    leftAt: integer("left_at"),
  },
  (table) => [
    primaryKey({ columns: [table.groupId, table.userId] }),
    // "Which groups am I in?": the group list and the membership check.
    index("group_member_user_idx").on(table.userId),
  ],
);

/**
 * One shared cost. Never updated and never deleted: a mistake is voided and
 * re-added (ADR-0018 §3), and a void by any member is allowed (§7) and audited.
 */
export const expense = sqliteTable(
  "expense",
  {
    id: text("id").primaryKey(),
    groupId: text("group_id")
      .notNull()
      .references(() => group.id, { onDelete: "restrict" }),
    description: text("description").notNull(),
    amountCents: integer("amount_cents").notNull(),
    /** Copied from the group at write time, and checked against it in code. */
    currency: text("currency").notNull(),
    /**
     * A calendar date, `YYYY-MM-DD`, and deliberately not a timestamp: a
     * receipt's date has no time zone (ADR-0018, Consequences).
     */
    spentOn: text("spent_on").notNull(),
    paidBy: text("paid_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdBy: text("created_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdAt: integer("created_at").notNull().default(nowUnixSeconds),
    /** R2 object key of the receipt photo, never the bytes (`REQ-D.3`). */
    receiptKey: text("receipt_key"),
    voidedAt: integer("voided_at"),
    voidedBy: text("voided_by").references(() => user.id, {
      onDelete: "restrict",
    }),
  },
  (table) => [
    // The group feed, newest first.
    index("expense_group_spent_idx").on(table.groupId, table.spentOn),
    check("expense_amount_positive", sql`${table.amountCents} > 0`),
    check("expense_currency_iso", sql`length(${table.currency}) = 3`),
    // A void is both columns or neither.
    check(
      "expense_void_complete",
      sql`(${table.voidedAt} IS NULL) = (${table.voidedBy} IS NULL)`,
    ),
  ],
);

/**
 * Each participant's share of an expense, computed once by `equalShares()` and
 * stored, so a balance never depends on re-running the rounding (ADR-0018 §1).
 * A share can be 0: 2p split three ways is 1/1/0.
 */
export const expenseShare = sqliteTable(
  "expense_share",
  {
    expenseId: text("expense_id")
      .notNull()
      .references(() => expense.id, { onDelete: "restrict" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    shareCents: integer("share_cents").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.expenseId, table.userId] }),
    // A member's balance sums their shares.
    index("expense_share_user_idx").on(table.userId),
    check("expense_share_non_negative", sql`${table.shareCents} >= 0`),
  ],
);

/**
 * A line from a receipt. It's informational: it doesn't affect who owes what
 * (ADR-0018 §1), but it's what gets categorised (ADR-0016) and embedded for
 * search (`REQ-D.4`).
 */
export const lineItem = sqliteTable(
  "line_item",
  {
    id: text("id").primaryKey(),
    expenseId: text("expense_id")
      .notNull()
      .references(() => expense.id, { onDelete: "restrict" }),
    /** The order the line appeared on the receipt, from 0. */
    position: integer("position").notNull(),
    description: text("description").notNull(),
    amountCents: integer("amount_cents").notNull(),
    category: text("category").notNull().default(UNCATEGORISED),
  },
  (table) => [
    index("line_item_expense_idx").on(table.expenseId, table.position),
    // The nightly backfill's query: `WHERE category = 'uncategorised'`.
    index("line_item_category_idx").on(table.category),
    check("line_item_category_known", sql`${table.category} IN (${categoryList})`),
    check("line_item_amount_non_negative", sql`${table.amountCents} >= 0`),
  ],
);

/**
 * "A paid B": the row the Durable Object exists to protect (`REQ-E.1`).
 * Immutable. It's valid only if the payer owes, the recipient is owed, and the
 * amount fits both (ADR-0018 §2), which is checked in code against the
 * balances, since a `CHECK` can't see other rows.
 */
export const settlement = sqliteTable(
  "settlement",
  {
    id: text("id").primaryKey(),
    groupId: text("group_id")
      .notNull()
      .references(() => group.id, { onDelete: "restrict" }),
    fromUser: text("from_user")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    toUser: text("to_user")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    amountCents: integer("amount_cents").notNull(),
    currency: text("currency").notNull(),
    recordedBy: text("recorded_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    createdAt: integer("created_at").notNull().default(nowUnixSeconds),
  },
  (table) => [
    index("settlement_group_created_idx").on(table.groupId, table.createdAt),
    check("settlement_amount_positive", sql`${table.amountCents} > 0`),
    check("settlement_currency_iso", sql`length(${table.currency}) = 3`),
    check("settlement_distinct_parties", sql`${table.fromUser} <> ${table.toUser}`),
    // Only the two people involved may record it (ADR-0018 §8).
    check(
      "settlement_recorded_by_party",
      sql`${table.recordedBy} IN (${table.fromUser}, ${table.toUser})`,
    ),
  ],
);

